[package]
name = "rs-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
csv = "1.3.0"
linregress = "0.5.3"
prometheus = "0.13.4"
serde = { version = "1.0.202", features = ["derive"]}
sysinfo = "0.30.12"
tokio = { version = "1.37.0", features = ["full"] }
