#!/usr/bin/env python3

import argparse
import datetime
import sys
import ansible_runner
import os

from benchmark import Benchmark
from error import MissingParameterError
from report import PrometheusMetricsReporter
import utils

import scenario

class CommandLineTool:
    def __init__(self):
        self.parser = argparse.ArgumentParser(description="Toolkit for benchmarking the geospatial processing workload")
        # self.parser.add_argument('-i', '--inventory', type=str, help='Inventory file', default='inventory.yml')
        self.subparsers = self.parser.add_subparsers(dest="command")

        # Create subparsers for "test" command
        self.run_parser = self.subparsers.add_parser("run", help='Run the benchmarking tests')
        # self.run_subparsers = self.test_parser.add_subparsers(dest="subcommand")
        # Subparser for the 'test run <scenario> <id>' subcommand
        # self.run_parser = self.run_subparsers.add_parser('run', help='Run the benchmarking test. test run <scenario_name> <scenario_path> ')
        self.run_parser.add_argument('-n','--name', type=str, help='The scenario unique name identifier')
        self.run_parser.add_argument('-d','--input-dir', type=str, help='Path of input directory in local computer')
        self.run_parser.add_argument('-f', '--file', type=str, help='Scenario file name')
        self.run_parser.add_argument('-r', '--repeat', type=int, help='The number of execution repeat', default=1)
        self.run_parser.add_argument('-c', '--converge', type=int, help='The number of converging percentage (in percent)', default=10)
        
        # Subparser for the 'result' subcommand
        self.result_parser = self.subparsers.add_parser('result', help='Manage benchmarking report result')
        # self.result_parser.add_argument('-n','--name', type=str, help='The scenario unique name identifier')
        self.result_subparsers = self.result_parser.add_subparsers(dest="subcommand")
        # Subparser for the 'result list' subcommand
        self.result_subparsers.add_parser('list', help='List all benchmarking scenario')
        # Subparser for the 'result remove <id>' subcommand
        self.result_remove_parser = self.result_subparsers.add_parser('remove', help='Delete benchmarking scenario given the scenario id')
        self.result_remove_parser.add_argument('id', type=str, help='The scenario id')
        # Subparser for the 'test save <id>' subcommand
        self.result_save_parser = self.result_subparsers.add_parser('save', help='Save benchmarking scenario to a specific local folder given the scenario id')
        self.result_save_parser.add_argument('id', type=str, help='The scenario id')
        # Subparser for the 'test save <id>' subcommand
        self.result_inspect_parser = self.result_subparsers.add_parser('inspect', help='Show benchmarking report result given the scenario id')
        self.result_inspect_parser.add_argument('id', type=str, help='The scenario id')
        # Subparser for the 'test display <id>' subcommand
        self.result_save_parser = self.result_subparsers.add_parser('display', help='Open Grafana dashboard given the scenario id')
        self.result_save_parser.add_argument('id', type=str, help='The scenario id')

        # Create subparsers for "install" command
        self.snapshot_parser = self.subparsers.add_parser("install", help='Install required packages')
        
        # Create subparsers for "monitor" command
        self.snapshot_parser = self.subparsers.add_parser("monitor", help='Monitor the benchmarking')

    def run(self):
        args = self.parser.parse_args()
        # inventory_path = os.path.abspath(args.inventory)
        
        if args.command == 'run':
            self.handle_run(args)
            # print(args)
        elif args.command == 'result':
            # self.handle_snapshot(args, "")
            print(args)
        elif args.command == 'install':
            # self.handle_install(args, "")
            print(args)
        elif args.command == 'monitor':
            # self.handle_install(args, "")
            print(args)
        else:
            self.parser.print_help()

    def handle_run(self, args, inventory_path=""):
        # Get the script file name
        scenario_file = os.path.abspath(args.file)

        try:
            # Load testing scenario
            test_scenario = scenario.load_scenario(scenario_file, args)
            # Run the bencmark based on parsed scenario
            benchmark = Benchmark()
            benchmark.run(test_scenario)
            # print(args.subcommand)
            print(test_scenario)
        except MissingParameterError as e:
            print(e)
            sys.exit(1)
    
    def handle_report(self, args):
        if args.subcommand == "list":
            benchmark = Benchmark()
            benchmark.list_all_results()
        elif args.subcommand == "report":
            # Get scenario name
            scenario_name = args.name
            benchmark = Benchmark()
            instance = benchmark.get_test_instance(scenario_name)
            if instance is not None:
                test_name  = instance["test_name"]
                start_time = datetime.datetime.fromtimestamp(instance["start_time"])
                end_time = datetime.datetime.fromtimestamp(instance["end_time"])
                # end_time = datetime.datetime.now()
                # start_time = end_time - datetime.timedelta(hours=1)
                print(f"Start time: {start_time}. End time: {end_time}")
                reporter = PrometheusMetricsReporter(url="http://18.197.58.197:9090", disable_ssl=True)
                reporter.generate_report(start_time=start_time, end_time=end_time, test_name=test_name)
        else:
            self.parser.print_help()
    
    def handle_snapshot(self, args, inventory_path):
        print(args.subcommand)
        #print(f"{args.greet}, {args.name}!")

    def handle_install(self, args, inventory_path):
        r = ansible_runner.interface.run(
                private_data_dir = 'ansible' ,
                playbook='install.yml',
                inventory=inventory_path
            )



if __name__ == "__main__":
    tool = CommandLineTool()
    tool.run()
