[project]
name = "geobench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-runner==2.3.6",
    "certifi==2024.2.2",
    "charset-normalizer==3.3.2",
    "contourpy==1.2.1",
    "cycler==0.12.1",
    "dateparser==1.2.0",
    "docutils==0.21.2",
    "fonttools==4.51.0",
    "httmock==1.4.0",
    "idna==3.7",
    "jinja2==3.1.4",
    "kiwisolver==1.4.5",
    "lockfile==0.12.2",
    "markupsafe==2.1.5",
    "matplotlib==3.9.0",
    "numpy==1.26.4",
    "packaging==24.0",
    "pandas==2.2.2",
    "pexpect==4.9.0",
    "pillow==11.0.0",
    "plotly==5.22.0",
    "prometheus-api-client==0.5.5",
    "psutil==5.9.8",
    "ptyprocess==0.7.0",
    "pyparsing==3.1.2",
    "python-daemon==3.0.1",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.1",
    "pyyaml==6.0.1",
    "regex==2024.5.15",
    "requests==2.32.2",
    "setuptools==70.0.0",
    "six==1.16.0",
    "tenacity==8.3.0",
    "tzdata==2024.1",
    "tzlocal==5.2",
    "urllib3==2.2.1"
]
