"""Command line interface module."""

import argparse
import logging
import os
import sys

from .executor import get_executors
from .executor.program import ProgramExecutor
from .scenario import Scenario
from .utils import ConfigOptionAction

logger = logging.getLogger(__name__)


class ArgumentDefaultsHelpFormatterNoNone(argparse.ArgumentDefaultsHelpFormatter):
    """Argument help formatter that omits empty default values."""

    def _get_help_string(self, action):
        if action.default is None:
            return action.help
        return super()._get_help_string(action)


class CLI:
    """Command line interface class."""

    def __init__(self):
        """Initialize command line interface object."""

        self.parser = argparse.ArgumentParser(
            description="Benchmarking toolkit for geospatial processing workflows.",
            formatter_class=ArgumentDefaultsHelpFormatterNoNone,
        )
        self.parser.add_argument(
            "-t",
            "--type",
            type=str,
            choices=[
                id
                for id, executor in get_executors().items()
                if issubclass(executor, ProgramExecutor)
            ],
            help="Scenario type",
            default="shell",
        )
        self.parser.add_argument(
            "-n",
            "--name",
            type=str,
            help="Scenario name",
        )
        self.parser.add_argument(
            "-r",
            "--repeat",
            type=int,
            help="Number of repeats (default: 1)",
        )
        self.parser.add_argument(
            "-i",
            "--input",
            dest="inputs",
            action=ConfigOptionAction,
            help="Input file as key=value (can be repeated)",
        )
        self.parser.add_argument(
            "-o",
            "--output",
            dest="outputs",
            action=ConfigOptionAction,
            help="Output file as key=value (can be repeated)",
        )
        self.parser.add_argument(
            "-a",
            "--arg",
            action=ConfigOptionAction,
            help="Argument as key=value (can be repeated)",
        )
        self.parser.add_argument(
            "-w",
            "--wait",
            type=float,
            help="Idle wait time before each run, in seconds (default: 5.0)",
        )
        self.parser.add_argument(
            "-m",
            "--monitor",
            type=float,
            help="Monitoring duration before and after each run, in seconds (default: 5.0)",
        )
        self.parser.add_argument(
            "--archive",
            type=str,
            choices=["none", "both", "input", "output"],
            help="File types to archive (default: both)",
        )
        self.parser.add_argument(
            "--workdir",
            type=str,
            help="Working directory (default: current working directory)",
        )
        self.parser.add_argument(
            "--basedir",
            type=str,
            help="Base directory (default: current working directory)",
        )
        self.parser.add_argument(
            "--outdir",
            type=str,
            help="Output directory (default: autogenerated from the scenario name)",
        )
        self.parser.add_argument(
            "--venv",
            type=str,
            help="Virtual environment path",
        )
        self.parser.add_argument(
            "--clear-outdir",
            action="store_true",
            help="Clear the output directory",
        )
        self.parser.add_argument(
            "--clear-outputs",
            action="store_true",
            help="Clear the output files",
        )
        self.parser.add_argument(
            "--clear-cache",
            action=argparse.BooleanOptionalAction,
            help="Clear the system caches (default: True)",
        )
        self.parser.add_argument(
            "-d",
            "--debug",
            action="store_true",
            help="Enable debug mode",
        )
        self.parser.add_argument(
            "command",
            type=str,
            help="Scenario filename or command",
        )
        self.parser.add_argument(
            "args",
            type=str,
            nargs=argparse.REMAINDER,
            help="Shell command arguments",
        )

    def run(self):
        """Run command line interface."""
        args = self.parser.parse_args()

        if args.debug:
            logging.basicConfig(
                level=logging.DEBUG,
                format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
            )

            for name in logging.root.manager.loggerDict:
                if name.startswith("geobench"):
                    logging.getLogger(name).setLevel(logging.DEBUG)

            logger.debug("Debugging enabled")
        else:
            logging.basicConfig(
                level=logging.INFO, format="%(levelname)s - %(message)s"
            )

        kwargs = {
            key: val
            for key, val in vars(args).items()
            if val is not None
            and key not in ["command", "arg", "args", "debug"]
        }

        kwargs["arguments"] = (args.arg or {}) | dict(enumerate(args.args or []))

        if args.command == "help":
            try:
                args.command = args.args.pop()
            except IndexError:
                self.parser.error("a command is required for help")
            executor = get_executors()[args.type]()
            help = executor.get_help(args.command)
            print(help)
            sys.exit()

        elif args.command.endswith((".yaml", ".yml")):
            del kwargs["type"]
            logger.debug("Loading scenario from %s", args.command)
            scenario = Scenario.load(os.path.abspath(args.command), **kwargs)

        else:
            logger.debug("Creating scenario from command line arguments")
            if args.command.endswith(".py"):
                logger.debug("Changing scenario type to Python")
                kwargs["type"] = "python"
                kwargs["name"] = os.path.basename(args.command)
            kwargs["command"] = args.command
            scenario = Scenario(**kwargs)

        scenario.benchmark()


def main():
    """Run command line interface."""
    cli = CLI()
    cli.run()
