"""Scenario module."""

import copy
import inspect
import itertools
import json
import os
import re
import shutil
import statistics
import time
import traceback
import unicodedata

import yaml

from .benchmark import Benchmark
from .executor import get_executors
from .report import calculate_run_summary, generate_html_report

import logging

logger = logging.getLogger(__name__)


class Scenario:
    """Scenario class."""

    def __init__(
        self,
        type: str,
        command,
        name: str | None = None,
        inputs: list | dict | None = None,
        outputs: list | dict | None = None,
        arguments: list | dict | None = None,
        repeat: int = 1,
        wait: float = 5.0,
        monitor: float | None = None,
        archive: str = "both",
        clear: bool = False,
        clear_outputs: bool = False,
        clear_cache: bool = True,
        workdir: str | None = None,
        basedir: str | None = None,
        outdir: str | None = None,
        venv: str | None = None,
        telemetry: dict | None = None,
    ):
        """Initialize scenario object.

        Args:
            type: Scenario type.
            command: Command.
            name: Optional scenario name.
            inputs: Optional list or dictionary of input files.
            outputs: Optional list or dictionary of output files.
            arguments: Optional list or dictionary of arguments.
            repeat: Number of repeats.
            wait: Idle wait time before each run, in seconds.
            monitor: Monitoring duration before and after each run, in seconds.
            archive: File types to archive. Options are 'none', 'both', 'input', 'output'.
            clear: If True, clear the output directory before running the benchmark.
            clear_outputs: If True, clear output files at the end of each run.
            clear_cache: If True, clear system caches before each run.
            workdir: Working directory path. It is also used as the root path of the input files.
                Defaults to the current working directory.
            basedir: Base directory path. It is used as the root path of the output directory, if is it not an absolute path.
                Defaults to the current working directory.
            outdir: Output directory path. Defaults to autogenerated path from the scenario name.
            venv: Optional virtual environment path.
            telemetry: Optional telemetry configuration.

        Raises:
            ValueError: if invalid scenario type.
            ValueError: if empty command.
            ValueError: if invalid arguments.
            ValueError: if invalid inputs.
            ValueError: if invalid outputs.
        """
        if not command:
            raise ValueError("Empty command")

        self.type = type
        self.name = name or f"{type} Scenario"
        self.command = command
        self.inputs = inputs or {}
        self.outputs = outputs or {}
        self.arguments = arguments or {}
        self.repeat = repeat or 1
        self.wait = wait or 0.0
        self.monitor = monitor
        self.archive = archive or "none"
        self.clear = clear
        self.clear_outputs = clear_outputs
        self.clear_cache = clear_cache
        self.telemetry = Benchmark.get_telemetry(telemetry)

        self.workdir = Benchmark.get_path(workdir)
        if not os.path.isdir(self.workdir):
            raise ValueError(f"Invalid working directory: {workdir}")

        self.basedir = Benchmark.get_path(basedir)
        if not os.path.isdir(self.basedir):
            raise ValueError(f"Invalid base directory: {basedir}")

        self.outdir = Benchmark.get_path(
            outdir or self.slugify(self.name), self.basedir
        )

        self.venv = Benchmark.get_path(venv) if venv else None
        if self.venv and not os.path.isdir(self.venv):
            raise ValueError(f"Invalid virtual environment: {venv}")

        if isinstance(self.outputs, dict):
            outputs = []
            for val in self.outputs.values():
                if isinstance(val, list):
                    outputs.extend(val)
                else:
                    outputs.append(val)
        else:
            outputs = self.outputs

        if isinstance(self.arguments, list):
            args = {key: val for key, val in enumerate(self.arguments)}
        else:
            args = self.arguments

        args = (
            args
            | (self.inputs if isinstance(self.inputs, dict) else {})
            | (self.outputs if isinstance(self.outputs, dict) else {})
        )
        args = {
            key: val if isinstance(val, list) else [val] for key, val in args.items()
        }

        if args:
            keys, vals = zip(*args.items())
            sets = [dict(zip(keys, items)) for items in itertools.product(*vals)]

        else:
            sets = [{}]

        self.sets = []
        for args in sets:
            item = {}

            if isinstance(self.inputs, dict):
                item["inputs"] = [args[key] for key in self.inputs.keys()]
            else:
                item["inputs"] = (
                    self.inputs if isinstance(self.inputs, list) else [self.inputs]
                )

            item["outputs"] = outputs
            item["arguments"] = args

            self.sets.append(item)

    @classmethod
    def slugify(cls, text: str) -> str:
        text = unicodedata.normalize("NFKD", text)
        text = text.encode("ascii", "ignore").decode("ascii").lower()
        text = re.sub(r"[^\w]", "_", text)
        text = re.sub(r"_+", "_", text)
        return text.strip("_")

    def _store(self, filename: str, content: dict):
        path = os.path.join(self.outdir, filename)
        with open(path, "w", encoding="utf-8") as file:
            json.dump(content, file, ensure_ascii=False, indent=2)

    def benchmark(self) -> dict:
        """Benchmark the scenario.

        Returns:
            Benchmarking results.
        """
        result = {}
        config = {
            "workdir": self.workdir,
            "venv": self.venv,
        }

        try:
            print(f"Running scenario {self.name}.")

            num_sets = len(self.sets)
            num_runs = num_sets * self.repeat
            print(
                "{} scenario {} with {} {}, {} {} in total.".format(
                    num_sets,
                    "sets" if num_sets > 1 else "set",
                    self.repeat,
                    "repeats" if self.repeat > 1 else "repeat",
                    num_runs,
                    "runs" if num_runs > 1 else "run",
                )
            )

            # Create executor
            print(f"Creating {self.type} executor.")
            executor_cls = get_executors().get(self.type)
            if not executor_cls:
                raise ValueError(f"Invalid executor type: {self.type}")

            executor = executor_cls(config)

            # Set up output directory
            print(f"Setting up output directory {self.outdir}.")
            if os.path.exists(self.outdir):
                if os.path.isdir(self.outdir):
                    if not self.clear:
                        print("Output directory exists, aborting.")
                        return {"error": "Output directory exists"}
                    else:
                        logger.debug(
                            "Removing existing output directory %s", self.outdir
                        )
                        shutil.rmtree(self.outdir)
                else:
                    print("Invalid output directory, aborting.")
                    return {"error": "Invalid output directory"}
            os.makedirs(self.outdir)

            # Store scenario
            print("Storing scenario.")
            self.save(os.path.join(self.outdir, "scenario.yaml"))

            # Store executor configuration
            print("Storing executor configuration.")
            result["config"] = executor.config
            self._store("result.json", result)

            # Start execution loop
            print("Executing the runs.")
            start_time = time.time()

            len_sets = len(str(num_sets))
            len_runs = len(str(self.repeat))

            set_summaries = []
            # For each scenario set
            for i, data in enumerate(self.sets):
                set_id = i + 1

                # Reset run summaries list
                run_summaries = []

                # For each repetation
                for j in range(self.repeat):
                    run_id = j + 1

                    print(f"Scenario set {set_id}, run {run_id}:")

                    path = os.path.join(
                        f"set_{set_id:0{len_sets}d}",
                        f"run_{run_id:0{len_runs}d}",
                    )

                    abs_path = os.path.join(self.outdir, path)
                    os.makedirs(abs_path, exist_ok=True)

                    benchmark = Benchmark(
                        wait=self.wait,
                        monitor=self.monitor,
                        telemetry=self.telemetry,
                        inputs=data["inputs"],
                        outputs=data["outputs"],
                        archive=self.archive,
                        clear=self.clear,
                        clear_cache=self.clear_cache,
                        workdir=self.workdir,
                        basedir=self.basedir,
                        outdir=abs_path,
                        metadata={
                            "set": set_id,
                            "run": run_id,
                            "arguments": data["arguments"],
                        },
                    )

                    # Modify run-specific arguments
                    args = copy.deepcopy(data["arguments"])

                    # Set input file paths
                    if isinstance(self.inputs, dict):
                        logger.debug("Modifying input paths")
                        for key in self.inputs.keys():
                            args[key] = os.path.normpath(
                                args[key]
                                if os.path.isabs(args[key])
                                else os.path.join(benchmark.workdir, args[key])
                            )

                    # Set output file paths
                    if isinstance(self.outputs, dict):
                        logger.debug("Modifying output paths")
                        for key in self.outputs.keys():
                            args[key] = os.path.normpath(
                                args[key]
                                if os.path.isabs(args[key])
                                else os.path.join(benchmark.workdir, args[key])
                            )

                    # Start benchmarking
                    benchmark.start(
                        process=lambda: executor.execute(self.command, args)
                    )

                    # Wait execution to finish
                    try:
                        executor.wait()

                    except Exception as err:
                        print(f"Command '{self.command}' failed with error: {err}")
                        print("Full stack trace:")
                        traceback.print_exception(err)

                    # Stop benchmarking
                    benchmark.stop()

                    # Clear outputs if required
                    if self.clear_outputs:
                        for key in self.outputs.keys():
                            path = args[key]
                            if not os.path.exists(path):
                                continue
                            print(f"Removing output file {path}")
                            for path in benchmark.get_related_files(path):
                                if not os.path.exists(path):
                                    continue
                                try:
                                    os.remove(path)
                                except Exception as err:
                                    logger.error(
                                        "Error removing output file %s: %s", path, err
                                    )

                    # Calculate run summary
                    run_summary = calculate_run_summary(benchmark.result)

                    # Append run summaries to the list for generating set runs summary and report
                    run_summaries.append(run_summary)

                # TODO: Generate summary of the set runs.
                total_runs = len(run_summaries)

                success_rate = (
                    (sum(1 for run in run_summaries if run["success"]) / total_runs)
                    if total_runs > 0
                    else 0
                )

                # Calculate average and standard deviation of execution time for all runs in a set
                run_time_list = [
                    run["run_time"] for run in run_summaries if "run_time" in run
                ]
                avg_run_time = statistics.mean(run_time_list) if run_time_list else 0
                stdev_run_time = (
                    statistics.stdev(run_time_list) if len(run_time_list) > 1 else 0
                )

                set_summary = {
                    "set": set_id,
                    "arguments": args,
                    "total": total_runs,
                    "success": success_rate,
                    "avg_run_time": avg_run_time,
                    "stdev_run_time": stdev_run_time,
                    "runs": run_summaries,
                }
                # Append set summary to the list for generating report
                set_summaries.append(set_summary)

                # TODO: Store summary of the set runs.
                set_summary_path = os.path.join(
                    self.outdir, f"set_{set_id:0{len_sets}d}", "summary.json"
                )
                self._store(set_summary_path, set_summary)

            duration = time.time() - start_time

            print(f"{num_sets} run(s) completed in {duration} s.")

            # TODO: Generate summary of all runs.
            # TODO: Store summary of all runs.

            # Generate report from set summaries
            # report_path = os.path.join(self.outdir, "report.html")
            # generate_html_report(
            #     system_data=result, set_summaries=set_summaries, output_path=report_path
            # )

        except KeyboardInterrupt:
            print("Benchmark run interrupted by user.")

        except Exception:
            raise

        return result

    @classmethod
    def load(path: str, **kwargs) -> "Scenario":
        """Load scenario from a YAML file and customize it keyword arguments, if required.

        See Scenario class initialization method for available arguments.

        Args:
            path: Path of the YAML file.
            **kwargs: Optional scenario arguments.

        Returns:
            Configured scenario.
        """
        # Load scenario from file
        logger.debug("Loading scenario from %s", path)
        with open(path, "r", encoding="utf-8") as file:
            scenario = yaml.safe_load(file)

        # Update scenario arguments
        logger.debug("Updating scenario with %s", kwargs)
        for key, val in kwargs.items():
            if isinstance(val, dict) and isinstance(scenario.get(key), dict):
                scenario[key].update(val)
            else:
                scenario[key] = val

        # Set scenario name from the filename, if required
        if not scenario.get("name"):
            scenario["name"] = os.path.splitext(os.path.basename(path))[0]

        # Sanitize arguments
        args = {}
        for key in inspect.signature(Scenario.__init__).parameters.keys():
            val = scenario.get(key)
            if key != "self" and val is not None:
                args[key] = val

        # Create scenario
        return Scenario(**args)

    def save(self, path: str):
        """Save scenario to a YAML file.

        Args:
            path: Path of the YAML file.
        """
        # Serialize scenario
        out = {
            "type": self.type,
            "command": self.command.__name__
            if callable(self.command)
            else self.command,
            "name": self.name,
            "inputs": self.inputs,
            "outputs": self.outputs,
            "arguments": self.arguments,
            "repeat": self.repeat,
            "wait": self.wait,
            "monitor": self.monitor,
            "archive": self.archive,
            "clear": self.clear or None,
            "clear_outputs": self.clear_outputs or None,
            "clear_cache": self.clear_cache,
            "workdir": self.workdir,
            "basedir": self.basedir,
            "outdir": self.outdir,
            "venv": self.venv,
            "telemetry": self.telemetry,
        }

        # Clean empty parameters
        out = {
            key: val
            for key, val in out.items()
            if val is not None and not (isinstance(val, (dict, list)) and len(val) == 0)
        }

        # Save scenario
        with open(path, "w", encoding="utf-8") as file:
            yaml.safe_dump(out, file, sort_keys=False, allow_unicode=True)
