"""Scenario module."""

import copy
import inspect
import itertools
import json
import logging
import os
import shutil
import statistics
import time
import traceback

import yaml

from .benchmark import Benchmark
from .executor import get_executors
from .report import calculate_run_summary, generate_html_report
from .utils import get_abs_path, is_empty, is_filename, serialize_dict, slugify

logger = logging.getLogger(__name__)


class Scenario:
    """Scenario class."""

    def __init__(
        self,
        executor: str,
        config: dict | None = None,
        arguments: list | dict | None = None,
        name: str | None = None,
        inputs: list | None = None,
        outputs: list | None = None,
        repeat: int = 1,
        wait: float = 5.0,
        monitor: float | None = None,
        archive: str = "both",
        clear_outdir: bool = False,
        clear_outputs: bool = True,
        clear_cache: bool = True,
        workdir: str | None = None,
        basedir: str | None = None,
        outdir: str | None = None,
        telemetry: dict | None = None,
    ):
        """Initialize scenario object.

        Args:
            executor: Executor.
            config: Executor configuration.
            arguments: Optional list or dictionary of arguments.
            name: Optional scenario name.
            inputs: Optional list of input file attributes.
            outputs: Optional list of of output file attributes.
            repeat: Number of repeats.
            wait: Idle wait time before each run, in seconds.
            monitor: Monitoring duration before and after each run, in seconds.
            archive: File types to archive. Options are 'none', 'both', 'input', 'output'.
            clear_outdir: If True, clear the output directory before running the benchmark.
            clear_outputs: If True, clear output files at the end of each run.
            clear_cache: If True, clear system caches before each run.
            workdir: Working directory path. It is also used as the root path of the input files.
                Defaults to the current working directory.
            basedir: Base directory path. It is used as the root path of the output directory, if is it not an absolute path.
                Defaults to the current working directory.
            outdir: Output directory path. Defaults to autogenerated path from the scenario name.
            telemetry: Optional telemetry configuration.

        Raises:
            ValueError: if invalid working directory.
            ValueError: if invalid base directory.
        """
        executor_cls = get_executors().get(executor)
        if not executor_cls:
            raise ValueError(f"Invalid executor: {executor}")

        self._executor = executor_cls(config)

        self.name = (
            name
            or f"{self._executor.get_info().name} {self._executor.get_config_code()} Scenario"
        )
        self.executor = executor
        self.config = config or {}
        self.inputs = inputs or []
        self.outputs = outputs or []
        self.arguments = arguments or {}
        self.repeat = repeat or 1
        self.wait = wait or 0.0
        self.monitor = monitor
        self.archive = archive or "none"
        self.clear_outdir = clear_outdir
        self.clear_outputs = clear_outputs
        self.clear_cache = clear_cache
        self.telemetry = Benchmark.get_telemetry(telemetry, duration=monitor)

        self.workdir = get_abs_path(workdir)
        if not os.path.isdir(self.workdir):
            raise ValueError(f"Invalid working directory: {workdir}")

        self.basedir = get_abs_path(basedir)
        if not os.path.isdir(self.basedir):
            raise ValueError(f"Invalid base directory: {basedir}")

        self.outdir = get_abs_path(
            outdir or slugify(f"{executor}_{self._executor.get_config_code()}"),
            self.basedir,
        )

        if isinstance(self.arguments, list):
            args = {key: val for key, val in enumerate(self.arguments)}
        else:
            args = self.arguments

        args = {
            key: val if isinstance(val, list) else [val] for key, val in args.items()
        }

        if args:
            keys, vals = zip(*args.items())
            sets = [dict(zip(keys, items)) for items in itertools.product(*vals)]

        else:
            sets = [{}]

        self.sets = []
        for args in sets:
            self.sets.append(
                {
                    "arguments": args,
                }
            )

    def _store(self, filename: str, content: dict):
        path = os.path.join(self.outdir, filename)
        with open(path, "w", encoding="utf-8") as file:
            json.dump(content, file, ensure_ascii=False, indent=2)

    def benchmark(self) -> dict:
        """Benchmark the scenario.

        Returns:
            Benchmarking results.
        """

        def _get_filenames(args: dict, vals: list[str]) -> list[str]:
            filenames = []

            for val in vals:
                filename = val if is_filename(val) else args.get(val)

                if is_empty(filename):
                    raise ValueError(f"Invalid filename argument: {val}")

                filenames.append(filename)

            return filenames

        result = {}

        try:
            logger.info("Running scenario: %s", self.name)

            num_sets = len(self.sets)
            num_runs = num_sets * self.repeat
            logger.info(
                "%d scenario %s with %d %s, %d %s in total",
                num_sets,
                "sets" if num_sets > 1 else "set",
                self.repeat,
                "repeats" if self.repeat > 1 else "repeat",
                num_runs,
                "runs" if num_runs > 1 else "run",
            )

            # Set up output directory
            logger.info("Setting up output directory: %s", self.outdir)
            if os.path.exists(self.outdir):
                if os.path.isdir(self.outdir):
                    if not self.clear_outdir:
                        logger.info("Output directory exists, aborting")
                        return {"error": "Output directory exists"}
                    else:
                        logger.debug(
                            "Removing existing output directory %s", self.outdir
                        )
                        shutil.rmtree(self.outdir)
                else:
                    logger.info("Invalid output directory, aborting")
                    return {"error": "Invalid output directory"}
            os.makedirs(self.outdir)

            # Store scenario
            logger.info("Storing scenario")
            self.save(os.path.join(self.outdir, "scenario.yaml"))

            # Store executor configuration
            logger.info("Storing executor configuration")
            result["config"] = serialize_dict(self._executor.config)
            result["metadata"] = serialize_dict(self._executor.metadata)
            self._store("result.json", result)

            # Start execution loop
            logger.info("Executing the runs")
            start_time = time.time()

            len_sets = len(str(num_sets))
            len_runs = len(str(self.repeat))

            set_summaries = []
            # For each scenario set
            for i, data in enumerate(self.sets):
                set_id = i + 1

                # Reset run summaries list
                run_summaries = []

                # For each repetation
                for j in range(self.repeat):
                    run_id = j + 1

                    logger.info("Scenario set %d, run %d:", set_id, run_id)

                    path = os.path.join(
                        f"set_{set_id:0{len_sets}d}",
                        f"run_{run_id:0{len_runs}d}",
                    )

                    abs_path = os.path.join(self.outdir, path)

                    benchmark = Benchmark(
                        wait=self.wait,
                        monitor=self.monitor,
                        telemetry=self.telemetry,
                        inputs=_get_filenames(data["arguments"], self.inputs),
                        outputs=_get_filenames(data["arguments"], self.outputs),
                        archive=self.archive,
                        clear_outdir=self.clear_outdir,
                        clear_outputs=self.clear_outputs,
                        clear_cache=self.clear_cache,
                        workdir=self.workdir,
                        basedir=self.basedir,
                        outdir=abs_path,
                        metadata={
                            "set": set_id,
                            "run": run_id,
                            "arguments": data["arguments"],
                        },
                    )

                    # Modify run-specific arguments
                    args = copy.deepcopy(data["arguments"])

                    # Set input and output file arguments
                    for key, values in {
                        "input": self.inputs,
                        "output": self.outputs,
                    }.items():
                        logger.debug("Modifying %s arguments", key)
                        for val in values:
                            if is_filename(val):
                                continue
                            if is_empty(args.get(val)):
                                raise ValueError(f"Invalid {key} argument: {val}")
                            args[val] = get_abs_path(args[val], benchmark.workdir)

                    # Start benchmarking
                    benchmark.start(
                        process_factory=lambda args=args: self._executor.execute(args)
                    )

                    # Wait execution to finish
                    try:
                        result["result"] = self._executor.wait()

                    except Exception:
                        logger.exception("Executor failed with error")

                    # Stop benchmarking
                    benchmark.stop()

                    # Calculate run summary
                    run_summary = calculate_run_summary(benchmark.result)

                    # Append run summaries to the list for generating set runs summary and report
                    run_summaries.append(run_summary)

                # TODO: Generate summary of the set runs.
                total_runs = len(run_summaries)

                success_rate = (
                    (sum(1 for run in run_summaries if run["success"]) / total_runs)
                    if total_runs > 0
                    else 0
                )

                # Calculate average and standard deviation of execution time for all runs in a set
                run_time_list = [
                    run["run_time"] for run in run_summaries if "run_time" in run
                ]
                avg_run_time = statistics.mean(run_time_list) if run_time_list else 0
                stdev_run_time = (
                    statistics.stdev(run_time_list) if len(run_time_list) > 1 else 0
                )

                set_summary = {
                    "set": set_id,
                    "arguments": args,
                    "total": total_runs,
                    "success": success_rate,
                    "avg_run_time": avg_run_time,
                    "stdev_run_time": stdev_run_time,
                    "runs": run_summaries,
                }
                # Append set summary to the list for generating report
                set_summaries.append(set_summary)

                # TODO: Store summary of the set runs.
                set_summary_path = os.path.join(
                    self.outdir, f"set_{set_id:0{len_sets}d}", "summary.json"
                )
                self._store(set_summary_path, set_summary)

            duration = time.time() - start_time

            logger.info("%d run(s) completed in %0.2f s", num_sets, duration)

            # TODO: Generate summary of all runs.
            # TODO: Store summary of all runs.

            # Generate report from set summaries
            # report_path = os.path.join(self.outdir, "report.html")
            # generate_html_report(
            #     system_data=result, set_summaries=set_summaries, output_path=report_path
            # )

        except KeyboardInterrupt:
            logger.info("Benchmark run interrupted by user")

        except Exception:
            raise

        return result

    @classmethod
    def load(cls, path: str, **kwargs) -> "Scenario":
        """Load scenario from a YAML file and customize it with keyword arguments, if required.

        See Scenario class initialization method for available arguments.

        Args:
            path: Path of the YAML file.
            **kwargs: Optional scenario arguments.

        Returns:
            Configured scenario.
        """
        # Load scenario from file
        logger.debug("Loading scenario from %s", path)
        with open(path, "r", encoding="utf-8") as file:
            scenario = yaml.safe_load(file)

        # Update scenario arguments
        logger.debug("Updating scenario with %s", kwargs)
        for key, val in kwargs.items():
            if isinstance(val, dict) and isinstance(scenario.get(key), dict):
                scenario[key].update(val)
            else:
                scenario[key] = val

        # Set scenario name from the filename, if required
        if not scenario.get("name"):
            scenario["name"] = os.path.splitext(os.path.basename(path))[0]

        # Sanitize arguments
        args = {}
        for key in inspect.signature(Scenario.__init__).parameters:
            val = scenario.get(key)
            if key != "self" and val is not None:
                args[key] = val

        # Create scenario
        return Scenario(**args)

    def save(self, path: str):
        """Save scenario to a YAML file.

        Args:
            path: Path of the YAML file.
        """
        # Serialize scenario
        out = serialize_dict(
            {
                "name": self.name,
                "executor": self.executor,
                "config": self.config,
                "arguments": {
                    key: val if (not isinstance(val, list) or len(val) > 1) else val[0]
                    for key, val in self.arguments.items()
                },
                "inputs": self.inputs,
                "outputs": self.outputs,
                "repeat": self.repeat,
                "wait": self.wait,
                "monitor": self.monitor,
                "archive": self.archive,
                "clear_outdir": self.clear_outdir or None,
                "clear_outputs": self.clear_outputs or None,
                "clear_cache": self.clear_cache,
                "workdir": self.workdir,
                "basedir": self.basedir,
                "outdir": self.outdir,
                "telemetry": self.telemetry,
            }
        )

        # Save scenario
        with open(path, "w", encoding="utf-8") as file:
            yaml.safe_dump(out, file, sort_keys=False, allow_unicode=True)
