"""Scenario module."""

import copy
import inspect
import itertools
import json
import logging
import os
import re
import shutil
import statistics
import time
import traceback
import unicodedata

import yaml

from .benchmark import Benchmark
from .executor import get_executors
from .report import calculate_run_summary, generate_html_report
from .utils import serialize_dict

logger = logging.getLogger(__name__)


class Scenario:
    """Scenario class."""

    def __init__(
        self,
        executor: str,
        config: dict | None = None,
        name: str | None = None,
        inputs: list | None = None,
        outputs: list | None = None,
        arguments: list | dict | None = None,
        repeat: int = 1,
        wait: float = 5.0,
        monitor: float | None = None,
        archive: str = "both",
        clear_outdir: bool = False,
        clear_outputs: bool = False,
        clear_cache: bool = True,
        workdir: str | None = None,
        basedir: str | None = None,
        outdir: str | None = None,
        telemetry: dict | None = None,
    ):
        """Initialize scenario object.

        Args:
            executor: Executor.
            config: Executor configuration.
            name: Optional scenario name.
            inputs: Optional list of input file attributes.
            outputs: Optional list of of output file attributes.
            arguments: Optional list or dictionary of arguments.
            repeat: Number of repeats.
            wait: Idle wait time before each run, in seconds.
            monitor: Monitoring duration before and after each run, in seconds.
            archive: File types to archive. Options are 'none', 'both', 'input', 'output'.
            clear_outdir: If True, clear the output directory before running the benchmark.
            clear_outputs: If True, clear output files at the end of each run.
            clear_cache: If True, clear system caches before each run.
            workdir: Working directory path. It is also used as the root path of the input files.
                Defaults to the current working directory.
            basedir: Base directory path. It is used as the root path of the output directory, if is it not an absolute path.
                Defaults to the current working directory.
            outdir: Output directory path. Defaults to autogenerated path from the scenario name.
            telemetry: Optional telemetry configuration.

        Raises:
            ValueError: if invalid working directory.
            ValueError: if invalid base directory.
        """
        self.name = name or f"{executor} Scenario"
        self.executor = executor
        self.config = config or {}
        self.inputs = inputs or []
        self.outputs = outputs or []
        self.arguments = arguments or {}
        self.repeat = repeat or 1
        self.wait = wait or 0.0
        self.monitor = monitor
        self.archive = archive or "none"
        self.clear_outdir = clear_outdir
        self.clear_outputs = clear_outputs
        self.clear_cache = clear_cache
        self.telemetry = Benchmark.get_telemetry(telemetry, duration=monitor)

        self.workdir = Benchmark.get_path(workdir)
        if not os.path.isdir(self.workdir):
            raise ValueError(f"Invalid working directory: {workdir}")

        self.basedir = Benchmark.get_path(basedir)
        if not os.path.isdir(self.basedir):
            raise ValueError(f"Invalid base directory: {basedir}")

        self.outdir = Benchmark.get_path(
            outdir or self.slugify(self.name), self.basedir
        )

        if isinstance(self.arguments, list):
            args = {key: val for key, val in enumerate(self.arguments)}
        else:
            args = self.arguments

        args = {
            key: val if isinstance(val, list) else [val] for key, val in args.items()
        }

        if args:
            keys, vals = zip(*args.items())
            sets = [dict(zip(keys, items)) for items in itertools.product(*vals)]

        else:
            sets = [{}]

        self.sets = []
        for args in sets:
            self.sets.append(
                {
                    "arguments": args,
                }
            )

    @classmethod
    def slugify(cls, text: str) -> str:
        text = unicodedata.normalize("NFKD", text)
        text = text.encode("ascii", "ignore").decode("ascii").lower()
        text = re.sub(r"[^\w]", "_", text)
        text = re.sub(r"_+", "_", text)
        return text.strip("_")

    def _store(self, filename: str, content: dict):
        path = os.path.join(self.outdir, filename)
        with open(path, "w", encoding="utf-8") as file:
            json.dump(content, file, ensure_ascii=False, indent=2)

    def benchmark(self) -> dict:
        """Benchmark the scenario.

        Returns:
            Benchmarking results.
        """
        result = {}

        try:
            print(f"Running scenario: {self.name}.")

            num_sets = len(self.sets)
            num_runs = num_sets * self.repeat
            print(
                "{} scenario {} with {} {}, {} {} in total.".format(
                    num_sets,
                    "sets" if num_sets > 1 else "set",
                    self.repeat,
                    "repeats" if self.repeat > 1 else "repeat",
                    num_runs,
                    "runs" if num_runs > 1 else "run",
                )
            )

            # Create executor
            print(f"Creating {self.executor} executor.")
            executor_cls = get_executors().get(self.executor)
            if not executor_cls:
                raise ValueError(f"Invalid executor: {self.executor}")

            executor = executor_cls(self.config)

            # Set up output directory
            print(f"Setting up output directory: {self.outdir}")
            if os.path.exists(self.outdir):
                if os.path.isdir(self.outdir):
                    if not self.clear_outdir:
                        print("Output directory exists, aborting.")
                        return {"error": "Output directory exists"}
                    else:
                        logger.debug(
                            "Removing existing output directory %s", self.outdir
                        )
                        shutil.rmtree(self.outdir)
                else:
                    print("Invalid output directory, aborting.")
                    return {"error": "Invalid output directory"}
            os.makedirs(self.outdir)

            # Store scenario
            print("Storing scenario.")
            self.save(os.path.join(self.outdir, "scenario.yaml"))

            # Store executor configuration
            print("Storing executor configuration.")
            result["config"] = serialize_dict(executor.config)
            result["metadata"] = serialize_dict(executor.metadata)
            self._store("result.json", result)

            # Start execution loop
            print("Executing the runs.")
            start_time = time.time()

            len_sets = len(str(num_sets))
            len_runs = len(str(self.repeat))

            set_summaries = []
            # For each scenario set
            for i, data in enumerate(self.sets):
                set_id = i + 1

                # Reset run summaries list
                run_summaries = []

                # For each repetation
                for j in range(self.repeat):
                    run_id = j + 1

                    print(f"Scenario set {set_id}, run {run_id}:")

                    path = os.path.join(
                        f"set_{set_id:0{len_sets}d}",
                        f"run_{run_id:0{len_runs}d}",
                    )

                    abs_path = os.path.join(self.outdir, path)

                    benchmark = Benchmark(
                        wait=self.wait,
                        monitor=self.monitor,
                        telemetry=self.telemetry,
                        inputs=[data["arguments"][key] for key in self.inputs],
                        outputs=[data["arguments"][key] for key in self.outputs],
                        archive=self.archive,
                        clear_outdir=self.clear_outdir,
                        clear_cache=self.clear_cache,
                        workdir=self.workdir,
                        basedir=self.basedir,
                        outdir=abs_path,
                        metadata={
                            "set": set_id,
                            "run": run_id,
                            "arguments": data["arguments"],
                        },
                    )

                    # Modify run-specific arguments
                    args = copy.deepcopy(data["arguments"])

                    # Set input file paths
                    if self.inputs:
                        logger.debug("Modifying input paths")
                        for key in self.inputs:
                            args[key] = os.path.normpath(
                                args[key]
                                if os.path.isabs(args[key])
                                else os.path.join(benchmark.workdir, args[key])
                            )

                    # Set output file paths
                    if self.outputs:
                        logger.debug("Modifying output paths")
                        for key in self.outputs:
                            args[key] = os.path.normpath(
                                args[key]
                                if os.path.isabs(args[key])
                                else os.path.join(benchmark.workdir, args[key])
                            )

                    # Start benchmarking
                    benchmark.start(process=lambda args=args: executor.execute(args))

                    # Wait execution to finish
                    try:
                        result["result"] = executor.wait()

                    except Exception as err:  # noqa: BLE001
                        print(f"Executor failed with error: {err}")
                        print("Full stack trace:")
                        traceback.print_exception(err)

                    # Stop benchmarking
                    benchmark.stop()

                    # Clear outputs if required
                    if self.clear_outputs:
                        for key in self.outputs:
                            path = args[key]
                            if not os.path.exists(path):
                                continue
                            print(f"Removing output file {path}")
                            for related_path in benchmark.get_related_files(path):
                                if not os.path.exists(related_path):
                                    continue
                                try:
                                    os.remove(related_path)
                                except OSError as err:
                                    logger.error(
                                        "Error removing output file %s: %s",
                                        related_path,
                                        err,
                                    )

                    # Calculate run summary
                    run_summary = calculate_run_summary(benchmark.result)

                    # Append run summaries to the list for generating set runs summary and report
                    run_summaries.append(run_summary)

                # TODO: Generate summary of the set runs.
                total_runs = len(run_summaries)

                success_rate = (
                    (sum(1 for run in run_summaries if run["success"]) / total_runs)
                    if total_runs > 0
                    else 0
                )

                # Calculate average and standard deviation of execution time for all runs in a set
                run_time_list = [
                    run["run_time"] for run in run_summaries if "run_time" in run
                ]
                avg_run_time = statistics.mean(run_time_list) if run_time_list else 0
                stdev_run_time = (
                    statistics.stdev(run_time_list) if len(run_time_list) > 1 else 0
                )

                set_summary = {
                    "set": set_id,
                    "arguments": args,
                    "total": total_runs,
                    "success": success_rate,
                    "avg_run_time": avg_run_time,
                    "stdev_run_time": stdev_run_time,
                    "runs": run_summaries,
                }
                # Append set summary to the list for generating report
                set_summaries.append(set_summary)

                # TODO: Store summary of the set runs.
                set_summary_path = os.path.join(
                    self.outdir, f"set_{set_id:0{len_sets}d}", "summary.json"
                )
                self._store(set_summary_path, set_summary)

            duration = time.time() - start_time

            print(f"{num_sets} run(s) completed in {duration} s.")

            # TODO: Generate summary of all runs.
            # TODO: Store summary of all runs.

            # Generate report from set summaries
            # report_path = os.path.join(self.outdir, "report.html")
            # generate_html_report(
            #     system_data=result, set_summaries=set_summaries, output_path=report_path
            # )

        except KeyboardInterrupt:
            print("Benchmark run interrupted by user.")

        except Exception:
            raise

        return result

    @classmethod
    def load(cls, path: str, **kwargs) -> "Scenario":
        """Load scenario from a YAML file and customize it with keyword arguments, if required.

        See Scenario class initialization method for available arguments.

        Args:
            path: Path of the YAML file.
            **kwargs: Optional scenario arguments.

        Returns:
            Configured scenario.
        """
        # Load scenario from file
        logger.debug("Loading scenario from %s", path)
        with open(path, "r", encoding="utf-8") as file:
            scenario = yaml.safe_load(file)

        # Update scenario arguments
        logger.debug("Updating scenario with %s", kwargs)
        for key, val in kwargs.items():
            if isinstance(val, dict) and isinstance(scenario.get(key), dict):
                scenario[key].update(val)
            else:
                scenario[key] = val

        # Set scenario name from the filename, if required
        if not scenario.get("name"):
            scenario["name"] = os.path.splitext(os.path.basename(path))[0]

        # Sanitize arguments
        args = {}
        for key in inspect.signature(Scenario.__init__).parameters:
            val = scenario.get(key)
            if key != "self" and val is not None:
                args[key] = val

        # Create scenario
        return Scenario(**args)

    def save(self, path: str):
        """Save scenario to a YAML file.

        Args:
            path: Path of the YAML file.
        """
        # Serialize scenario
        out = serialize_dict(
            {
                "name": self.name,
                "executor": self.executor,
                "config": self.config,
                "arguments": {
                    key: val if (not isinstance(val, list) or len(val) > 1) else val[0]
                    for key, val in self.arguments.items()
                },
                "inputs": self.inputs,
                "outputs": self.outputs,
                "repeat": self.repeat,
                "wait": self.wait,
                "monitor": self.monitor,
                "archive": self.archive,
                "clear_outdir": self.clear_outdir or None,
                "clear_outputs": self.clear_outputs or None,
                "clear_cache": self.clear_cache,
                "workdir": self.workdir,
                "basedir": self.basedir,
                "outdir": self.outdir,
                "telemetry": self.telemetry,
            }
        )

        # Save scenario
        with open(path, "w", encoding="utf-8") as file:
            yaml.safe_dump(out, file, sort_keys=False, allow_unicode=True)
