---
- name: Configure K3s Cluster
  hosts: master
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Install K3s server
      shell: |
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--disable traefik" sh -s - server --cluster-init --token {{ k3s_token }}
      environment:
        K3S_TOKEN: "{{ k3s_token }}"
      register: k3s_install_output

- name: Join worker nodes to K3s cluster
  hosts: all
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -
      environment:
        K3S_TOKEN: "{{ k3s_token }}"
        K3S_URL: "https://{{ master_ip }}:6443"

- name: Configure environment
  hosts: master
  vars_files:
    - vault.yml
  tasks:
    - name: Export KUBECONFIG
      shell: export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Install Helm
      shell: /tmp/get_helm.sh

    - name: Install Dask Kubernetes Operator using Helm
      shell: helm install --repo https://helm.dask.org --create-namespace -n dask-operator --generate-name dask-kubernetes-operator