---
- name: Configure K3s Cluster
  hosts: master
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Install K3s server
      shell: |
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--disable traefik" sh -s - server --cluster-init --token {{ k3s_token }}
      environment:
        K3S_TOKEN: "{{ k3s_token }}"
      register: k3s_install_output

- name: Join worker nodes to K3s cluster
  hosts: worker
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -
      environment:
        K3S_TOKEN: "{{ k3s_token }}"
        K3S_URL: "https://{{ master_ip }}:6443"

- name: Configure environment
  hosts: master
  vars_files:
    - vault.yml
  vars:
    kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
    profile_file: "/home/{{ ansible_user }}/.bash_profile"
  tasks:
    - name: Ensure the KUBECONFIG file exists
      stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_file

    - name: Fail if the KUBECONFIG file does not exist
      fail:
        msg: "KUBECONFIG file does not exist at {{ kubeconfig_path }}"
      when: not kubeconfig_file.stat.exists

    - name: Set permissions for the KUBECONFIG file
      file:
        path: "{{ kubeconfig_path }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      become: yes

    - name: Set KUBECONFIG variable in profile
      lineinfile:
        path: "{{ profile_file }}"
        line: 'export KUBECONFIG={{ kubeconfig_path }}'
        create: yes
        state: present

    # - name: Apply profile changes
    #   shell: source {{ profile_file }}
    #   ignore_errors: yes  # Ignore errors because the playbook will run this task non-interactively

    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Install Helm
      shell: /tmp/get_helm.sh

    - name: Install Dask Kubernetes Operator using Helm
      shell: helm install --repo https://helm.dask.org --create-namespace -n dask-operator --generate-name dask-kubernetes-operator
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml