---
- name: Restart K3s
  hosts: all
  become: true
  tasks:
    - name: Stop K3s service
      service:
        name: k3s
        state: stopped
        enabled: yes
      ignore_errors: yes

    - name: Kill any left-over K3s processes
      shell: |
        pids=$(ps aux | grep '[k]3s' | awk '{print $2}')
        if [ -n "$pids" ]; then
          kill -9 $pids
        fi

    - name: Remove K3s socket files
      file:
        path: /run/k3s*
        state: absent
        force: yes

    - name: Start K3s service
      service:
        name: k3s
        state: started
        enabled: yes

- name: Restart K3s agents
  hosts: worker
  become: true
  tasks:
    - name: Stop K3s agents service
      service:
        name: k3s-agent
        state: stopped
        enabled: yes
      ignore_errors: yes

    - name: Stop K3s agent service
      service:
        name: k3s-agent
        state: stopped
        enabled: yes
      ignore_errors: yes

    - name: Kill any left-over K3s processes
      shell: |
        pids=$(ps aux | grep '[k]3s' | awk '{print $2}')
        if [ -n "$pids" ]; then
          kill -9 $pids
        fi

    - name: Remove K3s socket files
      file:
        path: /run/k3s*
        state: absent
        force: yes

    - name: Start K3s agent service
      service:
        name: k3s-agent
        state: started
        enabled: yes